server:
  port: 9097

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CommentApp
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true